homepage/urls.py
from django.urls import path
from .views import index, experience

app_name = 'homepage'

urlpatterns = [
    path('', index, name='profile'),
    path('experience/', experience, name='exp'),
    # dilanjutkan ...
]

storylima/urls.py
from . import views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from .views import matakuliah

app_name = 'storylima'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:matkul_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('delete/<int:id>', views.delete, name='delete'),
]

storysatu/urls.py
from django.urls import path
from . import views

app_name = 'storysatu'

urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

storytiga/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('storysatu.urls')),
    path('schedule/', include('storylima.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

storylima/models.py
from django.db import models

class MataKuliah(models.Model):
    nama_matkul = models.CharField(max_length=250)
    dosen = models.CharField(max_length=500)
    jumlah_sks = models.PositiveIntegerField(default=3)
    deskripsi = models.CharField(max_length=1000)
    tahun_semester = models.CharField(max_length=250)
    ruang_kelas = models.CharField(max_length=300)

    def __str__(self):
        return self.nama_matkul

storysatu/models.py
from django.db import models

# Create your models here.

storylima/forms.py
from django import forms
from .models import *

class MataKuliahForm(forms.ModelForm):

    class Meta:
        model = MataKuliah
        fields = '__all__'

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'profile.html')

def experience(request):
    return render(request, 'experience.html')

storylima/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import MataKuliah
from .forms import *
from django.contrib import messages
from django.contrib.messages import constants

def index(request):
    semua_matkul = MataKuliah.objects.all()
    return render(request, 'matakuliah.html', {'all_matkul': semua_matkul})

def detail(request, matkul_id):
    matkul = get_object_or_404(MataKuliah, pk=matkul_id)
    return render(request, 'detail.html', {'matkul': matkul})

def add(request):
    if request.method == "POST":
        form = MataKuliahForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, (f"Course {request.POST['nama_matkul']} successfully added!"))
            redirect('/')
        else:
            messages.warning(request, ("Data invalid."))
            redirect('/')
    return render(request, 'add.html')

def delete(request, id):
    matkul = MataKuliah.objects.get(id=id)
    matkul.delete()
    messages.success(request, (f"Course {matkul} deleted"))
    return redirect('storylima:index')

storysatu/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'project.html')
# Create your views here.

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Navbar</title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="{%static 'homepage/style.css' %}" />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css?family=Poppins"
    rel="stylesheet"
  />
  <link
    href="https://fonts.googleapis.com/css?family=Mulish"
    rel="stylesheet"
  />
</head>

<body>

  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="#home">
        <img
          src="{%static 'images/FS.png' %}"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt="home"
          loading="lazy"
        />
        <span class="sr-only">(current)</span>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:profile' %}#about"
              >About</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:profile' %}#edu"
              >Education</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:profile' %}#skills"
              >Skills</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:exp' %}">Experience</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'storylima:index' %}"
              >Schedule</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:profile' %}#contact"
              >Contact</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content%}
    
  {% endblock content%}

<script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

homepage/templates/experience.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />

    <link rel="icon" href="{%static 'images/FS.png' %}" />
    <link rel="stylesheet" href="{%static 'style.css' %}" />
    <link
      href="https://fonts.googleapis.com/css?family=Poppins"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Mulish"
      rel="stylesheet"
    />

    <title>Shafna | Experience</title>

    <style>
      body {
        position: absolute;
        width: 100%;
        height: 100%;
        overflow-x: scroll;
        background-image: url("{%static 'images/Desktop52.png' %}");
      }
    </style>
  </head>
  <body>
    {% include "base.html" %}

    <div id="exp" class="justify-content-center align-items-center">
      <div class="container">
        <div class="row">
          <div class="col text-center">
            <h1><b>Experience</b></h1>
          </div>
        </div>

        <section class="intro">
          <div class="container"></div>
        </section>

        <section class="timeline">
          <ul>
            <li>
              <div>
                <time>2014</time> <br />
                <b>Coordinator of Health Department</b> <br />OSIS SMP Labschool
                Cibubur
              </div>
            </li>
            <li>
              <div>
                <time>2018</time> <br /><b>Person in Charge of LPBB </b><br />
                CROPS Heritage
              </div>
            </li>
            <li>
              <div>
                <time>2020</time> <br />
                <b>Data Entry Internship </b><br />Stranas PK
              </div>
            </li>
            <li>
              <div>
                <time>2020</time><br />
                <b>Staff of Mentor and Participant</b> <br />BETIS 2020
              </div>
            </li>
            <li>
              <div>
                <time>2020</time><br />
                <b>Staff of Student Advocation and Welfare</b> <br />BEM
                Fasilkom UI
              </div>
            </li>
            <li>
              <div>
                <time>2020</time> <br /><b>Staff of Seminar</b> <br />COMPFEST
                13
              </div>
            </li>
            <li>
              <div>
                <time>2020</time><br />
                <b>Staff of Event</b> <br />OH Fasilkom 2020
              </div>
            </li>
          </ul>
        </section>
      </div>
    </div>

    <div id="footer" class="justify-content-center align-items-center">
      <div class="container">
        <p style="font-size: small">© 2020 Copyright Fikra Shafna</p>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
    <script src="{%static 'Scroll.js' %}"></script>
  </body>
</html>

homepage/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link rel="icon" href="{%static 'images/FS.png' %}" />
    <link rel="stylesheet" href="{%static 'style.css' %}" />
    <link
      href="https://fonts.googleapis.com/css?family=Poppins"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Mulish"
      rel="stylesheet"
    />

    <title>Shafna | Profile</title>

  
    <style>
      body {
        position: absolute;
        width: 100%;
        height: 100%;
        overflow-x: scroll;
        background-image: url("{%static 'images/Desktop3.png' %}");
      }

    </style>

  </head>

  <body>
    {% include "base.html" %}

    <div id="home" class="jumbotron jumbotron-fluid">
      <div class="container">
        <div class="row">
          <div class="col" style="padding: 7%;">
            <img src="{%static 'images/Group14.png' %}" class="img-fluid" alt="Responsive image" style="position: sticky;">
          </div>
          <div class="col" style="padding-top: 10%;">
            <div class="animated-title">
              <div class="text-top">
                <div>
                  <span><h2 style="color: black;">Hello</h2></span>
                  <span><h1 style="color: black;">I'm <b style="color: #E1B003;">Shafna</b>!</h1></span>
                </div>
              </div>
              <div class="text-bottom">
                <div><h4 style="font-style: italic; color:#535353;">this is my journey</h4></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div id="about">
      <div class="container mx-auto">
        <div class="row d-flex justify-content-center" style="padding-bottom: 7%;"><img src="{%static 'images/Group10.png' %}" class="img-fluid" alt="Responsive image"></div>
        <div class="row">
          <div class="col">
            <p class="about" style="padding-bottom: 2%;">About me</p>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p class="par-1 text-md-left" style="padding-top: 5%;">
              My name is Fikra Shafna. Everyone calls me Shafna. I’m a sophomore
              majoring in Information System at University of Indonesia. Since I
              was a child I’ve always been attracted to technology. I love art,
              travelling, and volunteering.
            </p>
          </div>
          <div class="col">
            <img
              src="{%static 'images/shafna.jpg' %}"
              class="img-fluid-photo"
              alt="Responsive image"
            />
          </div>
        </div>
      </div>
    </div>

    <div id="edu" class="justify-content-center align-items-center">
      <div class="container">
        <div class="row d-flex justify-content-center" style="padding-bottom: 7%;"><img src="{%static 'images/Group10.png' %}" class="img-fluid" alt="Responsive image"></div>
        <div class="row">
          <div class="col text-center" style="padding-bottom: 7%;">
            <h1><b>Education</b></h1>
          </div>
        </div>

        <section class="intro">
          <div class="container"></div>
        </section>

        <section class="timeline">
          <ul>
            <li>
              <div>
                <time>2019</time> <br /><b>University of Indonesia</b>  <br />Major :
                Information System
              </div>
            </li>
            <li>
              <div><time>2016</time> <br /><b>SMAN 61 Jakarta</b></div>
            </li>
            <li>
              <div><time>2013</time> <br /><b>SMP Labschool Cibubur</b></div>
            </li>
            <li>
              <div><time>2007</time> <br /><b>SDI Al-Azhar 23</b></div>
            </li>
          </ul>
        </section>
      </div>
    </div>

    <div id="skills" class="justify-content-center align-items-center">
      <div class="container">
        <div class="row d-flex justify-content-center" style="padding-bottom: 7%;"><img src="{%static 'images/Group10.png' %}" class="img-fluid" alt="Responsive image"></div>
        <div class="row">
          <div class="col text-center">
            <h1>Skills</h1>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p class="text-center">
              Python <br />
              Java <br />
              Illustrator<br />
              Microsoft Office<br>
              Acrylic & Water Painting<br /> Team Work <br />
              Creative Thinking 
            </p>
          </div>
        </div>
      </div>
    </div>

    <div id="contact">
      <div class="container">
        <div class="row d-flex justify-content-center" style="padding-bottom: 7%;"><img src="{%static 'images/Group10.png' %}" class="img-fluid" alt="Responsive image"></div>
        <div class="row d-flex justify-content-center align-items-center"> 
        <h2>Hit me up at:</h2></div> 
        <div class="row">
          <div class="d-flex justify-content-center align-items-center" >
            <a href="https://www.linkedin.com/in/fikra-shafna-rahmania-putri-setyawan-b69855159/" style="text-align: center;">
              <img
                src="{%static 'images/linkedin-logo-png-black-9.png' %}", width="15%">
              </a>
              <a href="https://www.instagram.com/shafnafkr/" style="text-align: center;"><img
                src="{%static 'images/instagram.png' %}"
                , width="15%">
              </a>
              <a href="mailto:shafna.fikra@gmail.com" style="text-align: center;"><img src="{%static 'images/mail-5.png' %}", width="15%"></a>
          </div>
        </div>
      </div>
  </div>


    <!-- Footer -->
    <div id="footer">
      <div class="container"><p style="font-size: small; text-align: center;">Copyright © 2020 Fikra Shafna</p></div>
    </div>
    <!-- Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
    <script src="{%static 'Scroll.js'%}"></script>
  </body>
</html>

storylima/templates/add.html
{% extends 'base1.html' %}
{% block content %}

<div class="container">
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-4" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
	{% endfor %}
  {% endif %}
    <form class="mt-5" method="POST">
      {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-5">
            <label>Course Name</label>
            <input type="text" class="form-control" id="nama_matkul" name="nama_matkul" required>          
          </div>
          <div class="form-group col-md-5">
            <label for="dosen">Lecturer</label>
            <input type="text" class="form-control" id="dosen" name="dosen" required>          
          </div>
					<div class="form-group col-md-2">
            <label for="sks">Credits</label>
            <input type="number" class="form-control" id="jumlah_sks" name="jumlah_sks" required>          
          </div>
        </div>
				<div class="form-row">
          <div class="form-group col-md-5">
            <label for="tahunAjar">Semester (ex: Gasal 2019/2020) </label>
            <input type="text" class="form-control" id="tahun_semester" name="tahun_semester" required>
          </div>
          <div class="form-group col-md-2">
            <label for="ruang">Room</label>
            <input type="text" class="form-control" id="ruang_kelas" name="ruang_kelas" required>
          </div>
        </div>
				<div class="form-group">
					<label for="deskripsi">Description</label>
					<textarea class="form-control" id="deskripsi" rows="3" name="deskripsi" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
      </form>
</div>
{% endblock content %}

storylima/templates/base1.html
<!DOCTYPE html>
{% load static %}
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Course</title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="icon" href="{%static 'images/FS.png' %}" />
  <link rel="stylesheet" href="{%static 's5style.css' %}" />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
    crossorigin="anonymous"
  />
  <link
    href="https://fonts.googleapis.com/css?family=Poppins"
    rel="stylesheet"
  />
  <link
    href="https://fonts.googleapis.com/css?family=Mulish"
    rel="stylesheet"
  />

  <style>
    body{
      margin-top: auto;
      padding-top: 10%;
      background-color:#f8f5f5;
    }
  </style>
</head>

<body>

  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'homepage:profile' %}#home">
        <img
          src="{%static 'images/FS.png' %}"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt="home"
          loading="lazy"
        />
        <span class="sr-only">(current)</span>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:profile' %}#about"
              >About</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:profile' %}#edu"
              >Education</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:profile' %}#skills"
              >Skills</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:exp' %}">Experience</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'storylima:index' %}"
              >Schedule</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:profile' %}#contact"
              >Contact</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content%}
    
  {% endblock content%}

<script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

storylima/templates/detail.html
{% extends 'base1.html' %}
{% block content %}

<div class="container my-4">
    <div class="jumbotron">
        <h1 class="display-4">{{ matkul.nama_matkul }}</h1>
        <p class="lead">{{ matkul.tahun_semester }}</p>
        <p>{{ matkul.deskripsi }}</p>
        <hr class="my-4">
        <div class="row">
            <h4 class="col-10 col-md-3">Room : <span class="badge badge-dark">{{ matkul.ruang_kelas }}</span></h4>
            <h4 class="col-10 col-md-3">Lecturer : <span class="badge badge-dark">{{ matkul.dosen }}</span></h4>
            <h4 class="col-10 col-md-3">Credits : <span class="badge badge-dark">{{ matkul.jumlah_sks }} SKS</span></h4>
        </div>
        <a class="btn btn-outline-dark mt-4" href="{% url 'storylima:index' %}" role="button">BACK</a>
    </div>
</div>
{% endblock content %}

storylima/templates/matakuliah.html
{% extends 'base1.html' %}
{% block content %}

<div class="container my-4" style="margin-top: 15%;">
    <a class="nav-link" href="{%url 'storylima:add' %}">Add Course<span class="sr-only">(current)</span></a>
  {% if messages %}
	{% for message in messages %}
		<div class="alert alert-warning alert-dismissible fade show mt-4" role="alert">
			{{ message }}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	{% endfor %}
    {% endif %}
    
  {%if all_matkul%}
        {% for matkul in all_matkul %}
        <div class="card mt-3">
                <div class="card-body d-flex justify-content-between flex-column flex-md-row">
                    <div>
                        <a href="{% url 'storylima:detail' matkul.id %}"><h5 class="card-title">{{ matkul.nama_matkul }}</h5></a>
                        <h6 class="card-subtitle mb-2 text-muted">{{ matkul.tahun_semester}}</h6>
                    </div>

                    
                    <a href="{% url 'storylima:delete' matkul.id %}" class="card-link text-danger mt-3 mt-md-0 mr-md-4 align-self-center">DELETE</a>
                </div>
        </div>
        {%endfor%}

    {%else%}
     <h3>You don't have any course.</h3>
{%endif%}
</div>
{% endblock content %}